language: cpp
install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
    - export PATH=/usr/local/bin:/usr/bin:${PATH}
    - echo ${CXX}
    - ${CXX} --version
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - valgrind
compiler:
    - clang
    - gcc
before_script:
    - mkdir build && cd build
    - cmake ..
    # cmake -GNinja ..
script:
    - cmake --build .
    - cmake --build . --target test
    - cd .. && rm -rf build
branches:
    only:
        - master
sudo: false
