language: cpp
compiler:
  - clang
  - gcc
before_script:
  - mkdir build
  - cd build
  - cmake ..
  # cmake -GNinja
script:
  - cmake --build .
  - cmake --build . --target test
  - cd .. && rm -rf build
branches:
  only:
    - master
